import { Post } from './types/interfaces';

const filmPosts: Post[] = [
  {
    id: '1',
    name: 'Pulp fiction',
    year: 2004,
    genre: 'Crime',
    imgName: 'pulp_fiction_bg',
    rating: 7.5,
    runtime: 80,
    description: 'Pulp Fiction is a 1994 American crime film written and directed by Quentin Tarantino, who conceived it with Roger Avary.[4] Starring John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames, and Uma Thurman, it tells several stories of crime in Los Angeles. The title refers to the pulp magazines and hardboiled crime novels popular during the mid-20th century, known for their graphic violence and punchy dialogue.',
  },
  {
    id: '2',
    name: 'Bohemian Rhapsody',
    year: 2003,
    genre: 'Documentary',
    imgName: 'pulp_fiction_bg',
    rating: 7,
    runtime: 85,
    description: 'Pulp Fiction is a 1994 American crime film written and directed by Quentin Tarantino, who conceived it with Roger Avary.[4] Starring John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames, and Uma Thurman, it tells several stories of crime in Los Angeles. The title refers to the pulp magazines and hardboiled crime novels popular during the mid-20th century, known for their graphic violence and punchy dialogue.',
  },
  {
    id: '3',
    name: 'Kill Bill: Vol 2',
    year: 1994,
    genre: 'Crime',
    imgName: 'pulp_fiction_bg',
    rating: 8,
    runtime: 90,
    description: 'Pulp Fiction is a 1994 American crime film written and directed by Quentin Tarantino, who conceived it with Roger Avary.[4] Starring John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames, and Uma Thurman, it tells several stories of crime in Los Angeles. The title refers to the pulp magazines and hardboiled crime novels popular during the mid-20th century, known for their graphic violence and punchy dialogue.',
  },
  {
    id: '4',
    name: 'Avengers: War of Infinity',
    year: 2004,
    genre: 'Comedy',
    imgName: 'pulp_fiction_bg',
    rating: 6.8,
    runtime: 120,
    description: 'Pulp Fiction is a 1994 American crime film written and directed by Quentin Tarantino, who conceived it with Roger Avary.[4] Starring John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames, and Uma Thurman, it tells several stories of crime in Los Angeles. The title refers to the pulp magazines and hardboiled crime novels popular during the mid-20th century, known for their graphic violence and punchy dialogue.',
  },
  {
    id: '5',
    name: 'Inception',
    year: 2003,
    genre: 'Horror',
    imgName: 'pulp_fiction_bg',
    rating: 5,
    runtime: 90,
    description: 'Pulp Fiction is a 1994 American crime film written and directed by Quentin Tarantino, who conceived it with Roger Avary.[4] Starring John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames, and Uma Thurman, it tells several stories of crime in Los Angeles. The title refers to the pulp magazines and hardboiled crime novels popular during the mid-20th century, known for their graphic violence and punchy dialogue.',
  },
  {
    id: '6',
    name: 'Reservoir dogs',
    year: 1994,
    genre: 'Crime',
    imgName: 'pulp_fiction_bg',
    rating: 7,
    runtime: 80,
    description: 'Pulp Fiction is a 1994 American crime film written and directed by Quentin Tarantino, who conceived it with Roger Avary.[4] Starring John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames, and Uma Thurman, it tells several stories of crime in Los Angeles. The title refers to the pulp magazines and hardboiled crime novels popular during the mid-20th century, known for their graphic violence and punchy dialogue.',
  },
];
export default filmPosts;
